[build]
builder = "DOCKERFILE"
dockerfilePath = "apache/Dockerfile"

[deploy]
startCommand = "apache2-foreground"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internal_port = 80
auto_deploy = true 